name: easy_form_fields
description: A set of pre-built form fields you can quickly import to do validation in various common scenarios.
version: 0.0.1
repository: https://github.com/justinmc/easy_form_fields
issue_tracker: https://github.com/justinmc/easy_form_fields/issues

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
